fix tests

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -22,14 +22,27 @@ jobs:
       with:
         python-version: ${{ matrix.python-version }}
 
+    - name: Display requirements.txt content
+      run: cat requirements.txt
+
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
         pip install -r requirements.txt
+        
+    - name: Check installed packages and mlflow path
+      run: |
+        echo "--- PIP LIST ---"
+        pip list
+        echo "--- MLFLOW PACKAGE INFO ---"
+        pip show mlflow
+        echo "--- TRYING TO FIND MLFLOW TRANSFORMERS PATH ---"
+        python -c "import mlflow.transformers; print(mlflow.transformers.__file__)" || echo "MLFLOW.TRANSFORMERS NOT FOUND BY PYTHON"
+
     
     - name: Download NLTK data
       run: python -m nltk.downloader punkt
 
     - name: Run tests with pytest
       run: |
-        pytest -v
+        python -m pytest -v
